backend:
  name: git-gateway

media_folder: static/img
public_folder: /img
site_url: https://smashtools.netlify.app

collections:
  - name: 'brawl-fighters'
    label: 'Brawl Fighters'
    folder: 'content/brawl/fighters'
    format: 'frontmatter'
    editor:
      preview: true
    fields:
      - { label: 'ID', name: 'id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image URL', name: 'imageUrl', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
